name: tfsec

env:
    env: ${{secrets.ENV}} 
    azs: ${{secrets.AZS}} 
    subnet_public_cidr_blocks: ${{secrets.SUBNET_PUBLIC_CIDR_BLOCKS}} 
    subnet_private_cidr_blocks: ${{secrets.SUBNET_PRIVATE_CIDR_BLOCKS}} 
    db_username : ${{secrets.DB_USERNAME}}
    db_password : ${{secrets.DB_PASSWORD}}
    name : ${{secrets.NAME}}

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  tfsec:
    permissions:
        id-token: write
        contents: read
        actions: read
          
    name: tfsec sarif report
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          # sarif_file: tfsec.sarif  
          soft_fail: true

      # - run: | 
      #     ls -la
      #     cat tfsec.sarif
      #     cat tfsec.checksums  

      # - name: Upload SARIF file
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     # Path to SARIF file relative to the root of the repository
      #     sarif_file: tfsec.sarif


     